run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: false
    enable-all: false
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/MysticFunds/mysticfunds
  goconst:
    min-len: 4
    min-occurrences: 5
  misspell:
    locale: US
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  funlen:
    lines: 130
    statements: 80

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - funlen
    - path: proto/
      linters:
        - all
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - staticcheck
      text: "SA1019: grpc.Dial is deprecated"

  exclude-use-default: false
  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
    - "Error return value of .*.Rollback. is not checked"
    - "rows.Err must be checked"
    - "shadow: declaration of \"err\" shadows declaration"
    - "rand.Seed has been deprecated"
    - "at least one file in a package should have a package comment"
  max-issues-per-linter: 50
  max-same-issues: 3

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - dupl
      severity: info