databases:
  - name: mysticfunds-postgres
    databaseName: mysticfunds
    user: mysticfunds
    plan: free

services:
  - type: worker
    name: migrations
    env: docker
    dockerfilePath: scripts/Dockerfile.migrations
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: mysticfunds-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mysticfunds-postgres
          property: port
      - key: DB_USER
        fromDatabase:
          name: mysticfunds-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mysticfunds-postgres
          property: password

  - type: worker
    name: auth-service
    env: docker
    dockerfilePath: cmd/auth-service/Dockerfile
    plan: free
    dependsOn:
      - migrations
    envVars:
      - key: GRPC_PORT
        value: 50051
      - key: LOG_LEVEL
        value: info
      - key: JWT_SECRET
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: mysticfunds-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mysticfunds-postgres
          property: port
      - key: DB_USER
        fromDatabase:
          name: mysticfunds-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mysticfunds-postgres
          property: password
      - key: DB_NAME
        value: auth

  - type: worker
    name: wizard-service
    env: docker
    dockerfilePath: cmd/wizard-service/Dockerfile
    plan: free
    dependsOn:
      - migrations
    envVars:
      - key: GRPC_PORT
        value: 50052
      - key: LOG_LEVEL
        value: info
      - key: DB_HOST
        fromDatabase:
          name: mysticfunds-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mysticfunds-postgres
          property: port
      - key: DB_USER
        fromDatabase:
          name: mysticfunds-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mysticfunds-postgres
          property: password
      - key: DB_NAME
        value: wizard

  - type: worker
    name: mana-service
    env: docker
    dockerfilePath: cmd/mana-service/Dockerfile
    plan: free
    dependsOn:
      - migrations
    envVars:
      - key: GRPC_PORT
        value: 50053
      - key: LOG_LEVEL
        value: info
      - key: DB_HOST
        fromDatabase:
          name: mysticfunds-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mysticfunds-postgres
          property: port
      - key: DB_USER
        fromDatabase:
          name: mysticfunds-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mysticfunds-postgres
          property: password
      - key: DB_NAME
        value: mana

  - type: web
    name: api-gateway
    env: docker
    dockerfilePath: cmd/api-gateway/Dockerfile
    plan: free
    dependsOn:
      - auth-service
      - wizard-service
      - mana-service
    envVars:
      - key: HTTP_PORT
        value: 8080
      - key: LOG_LEVEL
        value: info
      - key: AUTH_SERVICE_ADDR
        fromService:
          type: worker
          name: auth-service
          property: hostport
      - key: WIZARD_SERVICE_ADDR
        fromService:
          type: worker
          name: wizard-service
          property: hostport
      - key: MANA_SERVICE_ADDR
        fromService:
          type: worker
          name: mana-service
          property: hostport