// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/wizard/wizard.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Wizard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Realm       string                 `protobuf:"bytes,3,opt,name=realm,proto3" json:"realm,omitempty"`
	ManaBalance int64                  `protobuf:"varint,4,opt,name=mana_balance,json=manaBalance,proto3" json:"mana_balance,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Wizard) Reset() {
	*x = Wizard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wizard_wizard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wizard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wizard) ProtoMessage() {}

func (x *Wizard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wizard_wizard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wizard.ProtoReflect.Descriptor instead.
func (*Wizard) Descriptor() ([]byte, []int) {
	return file_proto_wizard_wizard_proto_rawDescGZIP(), []int{0}
}

func (x *Wizard) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Wizard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Wizard) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *Wizard) GetManaBalance() int64 {
	if x != nil {
		return x.ManaBalance
	}
	return 0
}

func (x *Wizard) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Wizard) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateWizardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Realm string `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
}

func (x *CreateWizardRequest) Reset() {
	*x = CreateWizardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wizard_wizard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWizardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWizardRequest) ProtoMessage() {}

func (x *CreateWizardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wizard_wizard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWizardRequest.ProtoReflect.Descriptor instead.
func (*CreateWizardRequest) Descriptor() ([]byte, []int) {
	return file_proto_wizard_wizard_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWizardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWizardRequest) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

type GetWizardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetWizardRequest) Reset() {
	*x = GetWizardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wizard_wizard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWizardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWizardRequest) ProtoMessage() {}

func (x *GetWizardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wizard_wizard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWizardRequest.ProtoReflect.Descriptor instead.
func (*GetWizardRequest) Descriptor() ([]byte, []int) {
	return file_proto_wizard_wizard_proto_rawDescGZIP(), []int{2}
}

func (x *GetWizardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateWizardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Realm string `protobuf:"bytes,3,opt,name=realm,proto3" json:"realm,omitempty"`
}

func (x *UpdateWizardRequest) Reset() {
	*x = UpdateWizardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wizard_wizard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWizardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWizardRequest) ProtoMessage() {}

func (x *UpdateWizardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wizard_wizard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWizardRequest.ProtoReflect.Descriptor instead.
func (*UpdateWizardRequest) Descriptor() ([]byte, []int) {
	return file_proto_wizard_wizard_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateWizardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateWizardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWizardRequest) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

type ListWizardsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize   int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNumber int32 `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
}

func (x *ListWizardsRequest) Reset() {
	*x = ListWizardsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wizard_wizard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWizardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWizardsRequest) ProtoMessage() {}

func (x *ListWizardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wizard_wizard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWizardsRequest.ProtoReflect.Descriptor instead.
func (*ListWizardsRequest) Descriptor() ([]byte, []int) {
	return file_proto_wizard_wizard_proto_rawDescGZIP(), []int{4}
}

func (x *ListWizardsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWizardsRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

type ListWizardsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wizards    []*Wizard `protobuf:"bytes,1,rep,name=wizards,proto3" json:"wizards,omitempty"`
	TotalCount int32     `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListWizardsResponse) Reset() {
	*x = ListWizardsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wizard_wizard_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWizardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWizardsResponse) ProtoMessage() {}

func (x *ListWizardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wizard_wizard_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWizardsResponse.ProtoReflect.Descriptor instead.
func (*ListWizardsResponse) Descriptor() ([]byte, []int) {
	return file_proto_wizard_wizard_proto_rawDescGZIP(), []int{5}
}

func (x *ListWizardsResponse) GetWizards() []*Wizard {
	if x != nil {
		return x.Wizards
	}
	return nil
}

func (x *ListWizardsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type DeleteWizardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteWizardRequest) Reset() {
	*x = DeleteWizardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wizard_wizard_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWizardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWizardRequest) ProtoMessage() {}

func (x *DeleteWizardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wizard_wizard_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWizardRequest.ProtoReflect.Descriptor instead.
func (*DeleteWizardRequest) Descriptor() ([]byte, []int) {
	return file_proto_wizard_wizard_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteWizardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteWizardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteWizardResponse) Reset() {
	*x = DeleteWizardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wizard_wizard_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWizardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWizardResponse) ProtoMessage() {}

func (x *DeleteWizardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wizard_wizard_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWizardResponse.ProtoReflect.Descriptor instead.
func (*DeleteWizardResponse) Descriptor() ([]byte, []int) {
	return file_proto_wizard_wizard_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteWizardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_wizard_wizard_proto protoreflect.FileDescriptor

var file_proto_wizard_wizard_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x2f, 0x77,
	0x69, 0x7a, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x77, 0x69, 0x7a,
	0x61, 0x72, 0x64, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdb, 0x01, 0x0a, 0x06, 0x57, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x6e,
	0x61, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x6d, 0x61, 0x6e, 0x61, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x22, 0x3f, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x7a, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65,
	0x61, 0x6c, 0x6d, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x57, 0x69, 0x7a, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4f, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x57, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x22, 0x52, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74,
	0x57, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x60, 0x0a, 0x13,
	0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x77, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x77, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x2e, 0x57, 0x69,
	0x7a, 0x61, 0x72, 0x64, 0x52, 0x07, 0x77, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x73, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x25,
	0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57,
	0x69, 0x7a, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xdd, 0x02, 0x0a, 0x0d, 0x57, 0x69, 0x7a, 0x61,
	0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x12, 0x1b, 0x2e, 0x77, 0x69, 0x7a, 0x61,
	0x72, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x77, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x2e,
	0x57, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x57,
	0x69, 0x7a, 0x61, 0x72, 0x64, 0x12, 0x18, 0x2e, 0x77, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x2e, 0x47,
	0x65, 0x74, 0x57, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0e, 0x2e, 0x77, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x2e, 0x57, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x22,
	0x00, 0x12, 0x3d, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x69, 0x7a, 0x61, 0x72,
	0x64, 0x12, 0x1b, 0x2e, 0x77, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x57, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e,
	0x2e, 0x77, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x2e, 0x57, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x22, 0x00,
	0x12, 0x48, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x73, 0x12,
	0x1a, 0x2e, 0x77, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x7a,
	0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x77, 0x69,
	0x7a, 0x61, 0x72, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x57, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x12, 0x1b, 0x2e, 0x77, 0x69, 0x7a,
	0x61, 0x72, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x69, 0x7a, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x77, 0x69, 0x7a, 0x61, 0x72, 0x64,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6c, 0x69, 0x6e, 0x6f, 0x75, 0x72, 0x65, 0x64, 0x64,
	0x69, 0x6e, 0x65, 0x31, 0x2f, 0x6d, 0x79, 0x73, 0x74, 0x69, 0x63, 0x66, 0x75, 0x6e, 0x64, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_wizard_wizard_proto_rawDescOnce sync.Once
	file_proto_wizard_wizard_proto_rawDescData = file_proto_wizard_wizard_proto_rawDesc
)

func file_proto_wizard_wizard_proto_rawDescGZIP() []byte {
	file_proto_wizard_wizard_proto_rawDescOnce.Do(func() {
		file_proto_wizard_wizard_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_wizard_wizard_proto_rawDescData)
	})
	return file_proto_wizard_wizard_proto_rawDescData
}

var file_proto_wizard_wizard_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_wizard_wizard_proto_goTypes = []any{
	(*Wizard)(nil),                // 0: wizard.Wizard
	(*CreateWizardRequest)(nil),   // 1: wizard.CreateWizardRequest
	(*GetWizardRequest)(nil),      // 2: wizard.GetWizardRequest
	(*UpdateWizardRequest)(nil),   // 3: wizard.UpdateWizardRequest
	(*ListWizardsRequest)(nil),    // 4: wizard.ListWizardsRequest
	(*ListWizardsResponse)(nil),   // 5: wizard.ListWizardsResponse
	(*DeleteWizardRequest)(nil),   // 6: wizard.DeleteWizardRequest
	(*DeleteWizardResponse)(nil),  // 7: wizard.DeleteWizardResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_proto_wizard_wizard_proto_depIdxs = []int32{
	8, // 0: wizard.Wizard.created_at:type_name -> google.protobuf.Timestamp
	8, // 1: wizard.Wizard.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: wizard.ListWizardsResponse.wizards:type_name -> wizard.Wizard
	1, // 3: wizard.WizardService.CreateWizard:input_type -> wizard.CreateWizardRequest
	2, // 4: wizard.WizardService.GetWizard:input_type -> wizard.GetWizardRequest
	3, // 5: wizard.WizardService.UpdateWizard:input_type -> wizard.UpdateWizardRequest
	4, // 6: wizard.WizardService.ListWizards:input_type -> wizard.ListWizardsRequest
	6, // 7: wizard.WizardService.DeleteWizard:input_type -> wizard.DeleteWizardRequest
	0, // 8: wizard.WizardService.CreateWizard:output_type -> wizard.Wizard
	0, // 9: wizard.WizardService.GetWizard:output_type -> wizard.Wizard
	0, // 10: wizard.WizardService.UpdateWizard:output_type -> wizard.Wizard
	5, // 11: wizard.WizardService.ListWizards:output_type -> wizard.ListWizardsResponse
	7, // 12: wizard.WizardService.DeleteWizard:output_type -> wizard.DeleteWizardResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_wizard_wizard_proto_init() }
func file_proto_wizard_wizard_proto_init() {
	if File_proto_wizard_wizard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_wizard_wizard_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Wizard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wizard_wizard_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateWizardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wizard_wizard_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetWizardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wizard_wizard_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateWizardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wizard_wizard_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ListWizardsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wizard_wizard_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListWizardsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wizard_wizard_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteWizardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wizard_wizard_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteWizardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_wizard_wizard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wizard_wizard_proto_goTypes,
		DependencyIndexes: file_proto_wizard_wizard_proto_depIdxs,
		MessageInfos:      file_proto_wizard_wizard_proto_msgTypes,
	}.Build()
	File_proto_wizard_wizard_proto = out.File
	file_proto_wizard_wizard_proto_rawDesc = nil
	file_proto_wizard_wizard_proto_goTypes = nil
	file_proto_wizard_wizard_proto_depIdxs = nil
}
