// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/spell/spell.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Spell struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ManaCost    int64                  `protobuf:"varint,4,opt,name=mana_cost,json=manaCost,proto3" json:"mana_cost,omitempty"`
	Realm       string                 `protobuf:"bytes,5,opt,name=realm,proto3" json:"realm,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Spell) Reset() {
	*x = Spell{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spell_spell_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spell) ProtoMessage() {}

func (x *Spell) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spell_spell_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spell.ProtoReflect.Descriptor instead.
func (*Spell) Descriptor() ([]byte, []int) {
	return file_proto_spell_spell_proto_rawDescGZIP(), []int{0}
}

func (x *Spell) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Spell) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spell) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Spell) GetManaCost() int64 {
	if x != nil {
		return x.ManaCost
	}
	return 0
}

func (x *Spell) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *Spell) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateSpellRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ManaCost    int64  `protobuf:"varint,3,opt,name=mana_cost,json=manaCost,proto3" json:"mana_cost,omitempty"`
	Realm       string `protobuf:"bytes,4,opt,name=realm,proto3" json:"realm,omitempty"`
}

func (x *CreateSpellRequest) Reset() {
	*x = CreateSpellRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spell_spell_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSpellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpellRequest) ProtoMessage() {}

func (x *CreateSpellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spell_spell_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpellRequest.ProtoReflect.Descriptor instead.
func (*CreateSpellRequest) Descriptor() ([]byte, []int) {
	return file_proto_spell_spell_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSpellRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSpellRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSpellRequest) GetManaCost() int64 {
	if x != nil {
		return x.ManaCost
	}
	return 0
}

func (x *CreateSpellRequest) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

type GetSpellRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSpellRequest) Reset() {
	*x = GetSpellRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spell_spell_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpellRequest) ProtoMessage() {}

func (x *GetSpellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spell_spell_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpellRequest.ProtoReflect.Descriptor instead.
func (*GetSpellRequest) Descriptor() ([]byte, []int) {
	return file_proto_spell_spell_proto_rawDescGZIP(), []int{2}
}

func (x *GetSpellRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListSpellsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Realm      string `protobuf:"bytes,1,opt,name=realm,proto3" json:"realm,omitempty"`
	PageSize   int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNumber int32  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
}

func (x *ListSpellsRequest) Reset() {
	*x = ListSpellsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spell_spell_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSpellsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpellsRequest) ProtoMessage() {}

func (x *ListSpellsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spell_spell_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpellsRequest.ProtoReflect.Descriptor instead.
func (*ListSpellsRequest) Descriptor() ([]byte, []int) {
	return file_proto_spell_spell_proto_rawDescGZIP(), []int{3}
}

func (x *ListSpellsRequest) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *ListSpellsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSpellsRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

type ListSpellsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spells     []*Spell `protobuf:"bytes,1,rep,name=spells,proto3" json:"spells,omitempty"`
	TotalCount int32    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListSpellsResponse) Reset() {
	*x = ListSpellsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spell_spell_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSpellsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpellsResponse) ProtoMessage() {}

func (x *ListSpellsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spell_spell_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpellsResponse.ProtoReflect.Descriptor instead.
func (*ListSpellsResponse) Descriptor() ([]byte, []int) {
	return file_proto_spell_spell_proto_rawDescGZIP(), []int{4}
}

func (x *ListSpellsResponse) GetSpells() []*Spell {
	if x != nil {
		return x.Spells
	}
	return nil
}

func (x *ListSpellsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type LearnSpellRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WizardId int64 `protobuf:"varint,1,opt,name=wizard_id,json=wizardId,proto3" json:"wizard_id,omitempty"`
	SpellId  int64 `protobuf:"varint,2,opt,name=spell_id,json=spellId,proto3" json:"spell_id,omitempty"`
}

func (x *LearnSpellRequest) Reset() {
	*x = LearnSpellRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spell_spell_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LearnSpellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnSpellRequest) ProtoMessage() {}

func (x *LearnSpellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spell_spell_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnSpellRequest.ProtoReflect.Descriptor instead.
func (*LearnSpellRequest) Descriptor() ([]byte, []int) {
	return file_proto_spell_spell_proto_rawDescGZIP(), []int{5}
}

func (x *LearnSpellRequest) GetWizardId() int64 {
	if x != nil {
		return x.WizardId
	}
	return 0
}

func (x *LearnSpellRequest) GetSpellId() int64 {
	if x != nil {
		return x.SpellId
	}
	return 0
}

type LearnSpellResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LearnSpellResponse) Reset() {
	*x = LearnSpellResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spell_spell_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LearnSpellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnSpellResponse) ProtoMessage() {}

func (x *LearnSpellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spell_spell_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnSpellResponse.ProtoReflect.Descriptor instead.
func (*LearnSpellResponse) Descriptor() ([]byte, []int) {
	return file_proto_spell_spell_proto_rawDescGZIP(), []int{6}
}

func (x *LearnSpellResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LearnSpellResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CastSpellRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WizardId int64 `protobuf:"varint,1,opt,name=wizard_id,json=wizardId,proto3" json:"wizard_id,omitempty"`
	SpellId  int64 `protobuf:"varint,2,opt,name=spell_id,json=spellId,proto3" json:"spell_id,omitempty"`
	TargetId int64 `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
}

func (x *CastSpellRequest) Reset() {
	*x = CastSpellRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spell_spell_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastSpellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastSpellRequest) ProtoMessage() {}

func (x *CastSpellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spell_spell_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastSpellRequest.ProtoReflect.Descriptor instead.
func (*CastSpellRequest) Descriptor() ([]byte, []int) {
	return file_proto_spell_spell_proto_rawDescGZIP(), []int{7}
}

func (x *CastSpellRequest) GetWizardId() int64 {
	if x != nil {
		return x.WizardId
	}
	return 0
}

func (x *CastSpellRequest) GetSpellId() int64 {
	if x != nil {
		return x.SpellId
	}
	return 0
}

func (x *CastSpellRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type CastSpellResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ManaCost int64  `protobuf:"varint,3,opt,name=mana_cost,json=manaCost,proto3" json:"mana_cost,omitempty"`
}

func (x *CastSpellResponse) Reset() {
	*x = CastSpellResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spell_spell_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastSpellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastSpellResponse) ProtoMessage() {}

func (x *CastSpellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spell_spell_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastSpellResponse.ProtoReflect.Descriptor instead.
func (*CastSpellResponse) Descriptor() ([]byte, []int) {
	return file_proto_spell_spell_proto_rawDescGZIP(), []int{8}
}

func (x *CastSpellResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CastSpellResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CastSpellResponse) GetManaCost() int64 {
	if x != nil {
		return x.ManaCost
	}
	return 0
}

var File_proto_spell_spell_proto protoreflect.FileDescriptor

var file_proto_spell_spell_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x2f, 0x73, 0x70,
	0x65, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x70, 0x65, 0x6c, 0x6c,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xbb, 0x01, 0x0a, 0x05, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x6e, 0x61, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6d, 0x61, 0x6e, 0x61, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x65, 0x61, 0x6c, 0x6d, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0x7d, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x6d,
	0x61, 0x6e, 0x61, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x6d, 0x61, 0x6e, 0x61, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x6c,
	0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x22, 0x21,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x67, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x12, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x24, 0x0a, 0x06, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x2e, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x52, 0x06,
	0x73, 0x70, 0x65, 0x6c, 0x6c, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4b, 0x0a, 0x11, 0x4c, 0x65, 0x61, 0x72, 0x6e,
	0x53, 0x70, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x77, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x77, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x65,
	0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x70, 0x65,
	0x6c, 0x6c, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x12, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x53, 0x70, 0x65,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x67,
	0x0a, 0x10, 0x43, 0x61, 0x73, 0x74, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x77, 0x69, 0x7a, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x22, 0x64, 0x0a, 0x11, 0x43, 0x61, 0x73, 0x74, 0x53,
	0x70, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x6e, 0x61, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x6d, 0x61, 0x6e, 0x61, 0x43, 0x6f, 0x73, 0x74, 0x32, 0xc8, 0x02,
	0x0a, 0x0c, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38,
	0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x12, 0x19, 0x2e,
	0x73, 0x70, 0x65, 0x6c, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x73, 0x70, 0x65, 0x6c, 0x6c,
	0x2e, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53,
	0x70, 0x65, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x70, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x73,
	0x70, 0x65, 0x6c, 0x6c, 0x2e, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0a,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x73, 0x12, 0x18, 0x2e, 0x73, 0x70, 0x65,
	0x6c, 0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x43, 0x0a, 0x0a, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x12,
	0x18, 0x2e, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x53, 0x70, 0x65,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x70, 0x65, 0x6c,
	0x6c, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x09, 0x43, 0x61, 0x73, 0x74, 0x53, 0x70,
	0x65, 0x6c, 0x6c, 0x12, 0x17, 0x2e, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x2e, 0x43, 0x61, 0x73, 0x74,
	0x53, 0x70, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73,
	0x70, 0x65, 0x6c, 0x6c, 0x2e, 0x43, 0x61, 0x73, 0x74, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6c, 0x69, 0x6e, 0x6f, 0x75, 0x72, 0x65, 0x64,
	0x64, 0x69, 0x6e, 0x65, 0x31, 0x2f, 0x6d, 0x79, 0x73, 0x74, 0x69, 0x63, 0x66, 0x75, 0x6e, 0x64,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_spell_spell_proto_rawDescOnce sync.Once
	file_proto_spell_spell_proto_rawDescData = file_proto_spell_spell_proto_rawDesc
)

func file_proto_spell_spell_proto_rawDescGZIP() []byte {
	file_proto_spell_spell_proto_rawDescOnce.Do(func() {
		file_proto_spell_spell_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_spell_spell_proto_rawDescData)
	})
	return file_proto_spell_spell_proto_rawDescData
}

var file_proto_spell_spell_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_spell_spell_proto_goTypes = []any{
	(*Spell)(nil),                 // 0: spell.Spell
	(*CreateSpellRequest)(nil),    // 1: spell.CreateSpellRequest
	(*GetSpellRequest)(nil),       // 2: spell.GetSpellRequest
	(*ListSpellsRequest)(nil),     // 3: spell.ListSpellsRequest
	(*ListSpellsResponse)(nil),    // 4: spell.ListSpellsResponse
	(*LearnSpellRequest)(nil),     // 5: spell.LearnSpellRequest
	(*LearnSpellResponse)(nil),    // 6: spell.LearnSpellResponse
	(*CastSpellRequest)(nil),      // 7: spell.CastSpellRequest
	(*CastSpellResponse)(nil),     // 8: spell.CastSpellResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_proto_spell_spell_proto_depIdxs = []int32{
	9, // 0: spell.Spell.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: spell.ListSpellsResponse.spells:type_name -> spell.Spell
	1, // 2: spell.SpellService.CreateSpell:input_type -> spell.CreateSpellRequest
	2, // 3: spell.SpellService.GetSpell:input_type -> spell.GetSpellRequest
	3, // 4: spell.SpellService.ListSpells:input_type -> spell.ListSpellsRequest
	5, // 5: spell.SpellService.LearnSpell:input_type -> spell.LearnSpellRequest
	7, // 6: spell.SpellService.CastSpell:input_type -> spell.CastSpellRequest
	0, // 7: spell.SpellService.CreateSpell:output_type -> spell.Spell
	0, // 8: spell.SpellService.GetSpell:output_type -> spell.Spell
	4, // 9: spell.SpellService.ListSpells:output_type -> spell.ListSpellsResponse
	6, // 10: spell.SpellService.LearnSpell:output_type -> spell.LearnSpellResponse
	8, // 11: spell.SpellService.CastSpell:output_type -> spell.CastSpellResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_spell_spell_proto_init() }
func file_proto_spell_spell_proto_init() {
	if File_proto_spell_spell_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_spell_spell_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Spell); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spell_spell_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateSpellRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spell_spell_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetSpellRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spell_spell_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListSpellsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spell_spell_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ListSpellsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spell_spell_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*LearnSpellRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spell_spell_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*LearnSpellResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spell_spell_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CastSpellRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spell_spell_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CastSpellResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_spell_spell_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_spell_spell_proto_goTypes,
		DependencyIndexes: file_proto_spell_spell_proto_depIdxs,
		MessageInfos:      file_proto_spell_spell_proto_msgTypes,
	}.Build()
	File_proto_spell_spell_proto = out.File
	file_proto_spell_spell_proto_rawDesc = nil
	file_proto_spell_spell_proto_goTypes = nil
	file_proto_spell_spell_proto_depIdxs = nil
}
