FROM postgres:15-alpine

# Install migrate tool
RUN apk add --no-cache curl bash
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
RUN mv migrate /usr/local/bin/

# Copy migration files and scripts
COPY migrations/ /migrations/
COPY scripts/init-databases-and-migrate.sh ./scripts/init-databases-and-migrate.sh
RUN chmod +x ./scripts/init-databases-and-migrate.sh

CMD ["./scripts/init-databases-and-migrate.sh"]